# docker run --name web_nginx -d -v vol_nginx:/usr/share/nginx/html --newtwork net_nginx -p 8080:80 nginx
version: '3'
services:
  web:
    container_name: web_nginx
    ports:
      - "8080:80"
    image: nginx
    volumes:
      - "vol_nginx:/usr/share/nginx/html"
    networks:
      - net_nginx 

volumes:
  vol_nginx:

networks:
  net_nginx:
    driver: bridge

