version: '3'
services:
  # SonarQube
  # default user = admin
  # default pass = admin
  # sudo sysctl -w vm.max_map_count=262144
  sonarQube:
    image: sonarqube:latest
    container_name: sonarQube
    depends_on:
      - sonarQube_database
    environment:
      VIRTUAL_HOST: sonarq.295devops.com
      LETSENCRYPT_HOST: sonarq.295devops.com
      LETSENCRYPT_EMAIL: roxsrossve@gmail.com
      VIRTUAL_PORT: 9000
      SONAR_JDBC_URL: jdbc:postgresql://sonarQube_database:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - SonarQube_data:/opt/SonarQube/data
      - SonarQube_extensions:/opt/SonarQube/extensions
      - SonarQube_logs:/opt/SonarQube/logs
    ports:
      - 9000:9000
    restart: always  
    networks:
      - ci

  nginx-proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    networks:
      - ci 

  nginx-proxy-letsencrypt:
    container_name: nginx-proxy-letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    depends_on:
      - nginx-proxy
    volumes:
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/var/run/docker.sock:ro 
    networks:
      - ci   

  # SonarQube database
  sonarQube_database:
    image: postgres:latest
    container_name: sonarQube_database
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - SonarQube_postgresql:/var/lib/postgresql
      - SonarQube_postgresql_data:/var/lib/postgresql/data
    restart: always
    networks:
      - ci

volumes:
  html:
  certs:
  vhost:
  SonarQube_data:
  SonarQube_extensions:
  SonarQube_logs:
  SonarQube_postgresql:
  SonarQube_postgresql_data:
  postgresql:
  postgresql_data:

networks:
  ci:
    driver: bridge