pipeline {
    agent any
    environment {
        EC2INSTANCE = 'ec2-user@44.199.211.39'
    }

    stages {
        stage('Init') {
            steps {
                echo 'Stage Init'
            }
        }
        stage('Test') {
            steps {
                echo 'Stage Test'
            }
        }
        stage('Build') {
            steps {
                echo 'Stage Build'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Stage Deploy'
                sh 'touch prueba.txt'
                sshagent(['ssh-ec2']){
                 sh 'scp -o StrictHostKeyChecking=no prueba.txt ${EC2INSTANCE}:/home/ec2-user' 
                }
            }
        }
        stage('Notification') {
            steps {
                echo 'Stage Notify'
            }
        }
    }
}