apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
    version: v1
    env: prod
  annotations:
    owner: test
    url: https://google.com
spec:
  containers:
  - name: nginx-image
    image: nginx:alpine
    imagePullPolicy: Always
