version: '3'  

services:  
  front: 
    image: roxsross12/temperaturas_frontend
    container_name: front
    ports:
      - 80:3000
    networks:
      - temperatura 
    depends_on:
      - back

  back:
    image: roxsross12/temperaturas_backend
    container_name: back
    ports:
      - 5000:5000
    networks:
      - temperatura 

networks:
  temperatura:
    driver: bridge